### ISSUE TITLE
Support before/after stack creation and deletion tasks

### ISSUE THREAD

**Issue by erran-r7** [rapid7/convection#114]
Tasks can utilise information around the stack object and be used to perform operations in AWS or elsewhere as the user sees fit.

Today at Rapid7 we have internal support for this via monkey patching the stack create/delete methods to enumerate a registry of tasks to execute.

# Subtasks
- [x] Create a `before_create` task type.
- [x] Create a `after_create` task type.
- [x] Create a `before_delete` task type.
- [x] Create a `after_delete` task type.

**Comment by erran-r7** [comment]
cc @simonirwin-r7

**Comment by simonirwin-r7** [comment]
I think we should focus on this first.

The goal could be:
- create a VPC with a normal Convection template (strip it right down for speed)
- execute an `after_create` task to associate that VPC with the private Route53 Hosted Zone.  This task already exists.

**Comment by erran-r7** [comment]
> create a VPC with a normal Convection template (strip it right down for speed)

Done in the unit test found in #119. I'll extend it as an example convection repository that deals with hosted zones. May not be generic enough to open source at first but I'll work on that today.
